name: Unit Tests Mac-Windows

on:
  push:
    tags: ["*"] # Push events to every tag

jobs:
  run_build_tests:
    name: build_tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: build_test
        shell: bash
        run: scripts/test.sh
